package com.muhasib.aliascreation.demo

import com.muhasib.aliascreation.model.AccountItem

object DummyData {
    val dummyList = listOf(

        AccountItem("1", "Quantum Innovations", "Account", listOf("QTech", "QuantumCore", "QIN", "InnovateX")),
        AccountItem("2", "Stellar Solutions", "Account", listOf("StarTech", "StellarCore", "SSI", "GalaxyBiz")),
        AccountItem("31", "Quantum Processor", "Item", listOf("Q-Chip", "HyperCore", "NeuralProcessor", "LightSpeed CPU")),
        AccountItem("32", "Nano Fiber Cable", "Item", listOf("NFCord", "MicroStrand", "AtomicThread", "TitanWire")),
        AccountItem("33", "Holographic Display", "Item", listOf("HoloScreen", "3DProjector", "LightMatrix", "PhantomView")),
        AccountItem("34", "Plasma Battery", "Item", listOf("P-Cell", "IonPower", "EnergyOrb", "EverCharge")),
        AccountItem("35", "Neural Interface", "Item", listOf("MindLink", "BrainBridge", "SynapseConnector", "ThoughtGate")),
        AccountItem("36", "Gravity Boots", "Item", listOf("AntiGravShoes", "FloatWalkers", "ZeroG Boots", "SkyStriders")),
        AccountItem("3", "Nexus Enterprises", "Account", listOf("NexusCorp", "NXGroup", "NexusGlobal", "ConnectX")),
        AccountItem("4", "Aurora Systems", "Account", listOf("AuroraTech", "NorthernLights", "ASL", "DawnSolutions")),
        AccountItem("5", "Vertex Holdings", "Account", listOf("VXGroup", "PeakCapital", "VertexGlobal", "SummitVentures")),
        AccountItem("6", "Titan Industries", "Account", listOf("TitanCorp", "GiantEnterprises", "TIL", "ColossusGroup")),
        AccountItem("13", "TerraFirma Enterprises", "Account", listOf("TerraGroup", "EarthBound", "SolidGround", "TFE")),
        AccountItem("14", "Nova Industries", "Account", listOf("NovaTech", "Supernova", "NIL", "StellarGroup")),
        AccountItem("15", "Orion Capital", "Account", listOf("OrionGroup", "HunterInvest", "OCL", "ConstellationFund")),
        AccountItem("16", "Phoenix Ventures", "Account", listOf("PhoenixRise", "RebirthCapital", "PVL", "AshesGroup")),
        AccountItem("17", "Eclipse Solutions", "Account", listOf("EclipseTech", "ShadowSystems", "ESL", "UmbrellaGroup")),
        AccountItem("61", "Smart Paper", "Item", listOf("E-Sheet", "DigitalPulp", "iPage", "ReusableScroll")),
        AccountItem("62", "Nano Solar Cell", "Item", listOf("MicroSun", "PicoPanel", "QuantumCell", "AtomicHarvester")),
        AccountItem("63", "Bio Computer", "Item", listOf("OrganicProcessor", "NeuralNet", "DNA Drive", "LivingCPU")),
        AccountItem("64", "Plasma Cutter", "Item", listOf("StarEdge", "IonSlicer", "SunBlade", "FusionCutter")),
        AccountItem("65", "Holographic Map", "Item", listOf("3D Atlas", "LightGlobe", "ProjectionChart", "VirtualTerrain")),
        AccountItem("66", "Smart Concrete", "Item", listOf("iCement", "TechStone", "ProgrammableRock", "NanoPavement")),
        AccountItem("67", "Quantum Sensor", "Item", listOf("EntanglementDetector", "Q-Scanner", "ParticleFinder", "AtomicRadar")),
        AccountItem("68", "Neural Stimulator", "Item", listOf("BrainBoost", "SynapseActivator", "MindEnhancer", "CerebralPulse")),
        AccountItem("69", "Nano Vaccine", "Item", listOf("MicroShield", "PicoProtection", "AtomicDefense", "QuantumImmunity")), AccountItem("18", "Paragon Holdings", "Account", listOf("ParagonGroup", "ModelCorp", "PHL", "ExemplarVentures")),
        AccountItem("19", "Apex Systems", "Account", listOf("ApexTech", "PeakSolutions", "ASL", "SummitGroup")),
        AccountItem("20", "Infinitas Capital", "Account", listOf("InfinitasGroup", "ICL", "BoundlessFunds", "EternalVentures")),
        AccountItem("21", "Cascade Industries", "Account", listOf("CascadeGroup", "WaterfallCorp", "CIL", "TorrentHoldings")),
        AccountItem("22", "Monarch Ventures", "Account", listOf("MonarchGroup", "RoyalHoldings", "MVL", "RegalCapital")),
        AccountItem("23", "Triton Systems", "Account", listOf("TritonTech", "SeaGodSolutions", "TSL", "NeptuneGroup")),
        AccountItem("24", "Pegasus Capital", "Account", listOf("PegasusGroup", "WingedHorse", "PCL", "FlyHighVentures")),
        AccountItem("25", "Obelisk Holdings", "Account", listOf("ObeliskGroup", "PillarCorp", "OHL", "MonumentCapital")),
        AccountItem("26", "Helix Industries", "Account", listOf("HelixGroup", "SpiralCorp", "HIL", "DoubleStrand")),
        AccountItem("27", "Spectra Systems", "Account", listOf("SpectraTech", "PrismSolutions", "SSL", "RainbowGroup")),
        AccountItem("28", "Meridian Capital", "Account", listOf("MeridianGroup", "NoonVentures", "MCL", "HighPointFund")),
        AccountItem("29", "Polaris Holdings", "Account", listOf("PolarisGroup", "NorthStar", "PHL", "GuidingLight")),
        AccountItem("30", "Chronos Ventures", "Account", listOf("ChronosGroup", "TimeKeepers", "CVL", "TemporalFund")),
        AccountItem("37", "Smart Glass", "Item", listOf("iWindow", "ClearDisplay", "OptiPane", "VisionGlass")),
        AccountItem("38", "Nano Drone", "Item", listOf("MicroFlyer", "PicoCopter", "AtomWing", "BugDrone")),
        AccountItem("39", "Bio Sensor", "Item", listOf("LifeScanner", "VitalTrack", "PulseSense", "HealthMonitor")),
        AccountItem("40", "Solar Fabric", "Item", listOf("SunCloth", "PowerWeave", "PhotoTextile", "EnergyFleece")),
        AccountItem("41", "AI Assistant Pod", "Item", listOf("SmartSphere", "ThinkOrb", "IntelPod", "CogniBall")),
        AccountItem("42", "Water Purifier", "Item", listOf("AquaFilter", "PureFlow", "CleanSip", "HydroPure")),
        AccountItem("43", "Portable Lab", "Item", listOf("LabInABox", "MobileScience", "PocketResearcher", "FieldAnalyzer")),
        AccountItem("44", "Memory Crystal", "Item", listOf("DataGem", "StorageShard", "InfoQuartz", "KnowledgeStone")),
        AccountItem("45", "Smart Paint", "Item", listOf("ColorShift", "iCoat", "TechHue", "ProgrammablePigment")),
        AccountItem("46", "Voice Translator", "Item", listOf("LinguaLink", "BabelChip", "UniversalSpeaker", "PolyglotPod")),
        AccountItem("7", "Horizon Ventures", "Account", listOf("HorizonCapital", "HZGroup", "FutureScope", "SkylineInvest")),
        AccountItem("8", "Pinnacle Group", "Account", listOf("PinnacleHoldings", "PeakGroup", "PNL", "SummitCorp")),
        AccountItem("9", "Infinity Capital", "Account", listOf("InfiniteFunds", "IFC", "EndlessVentures", "LimitlessGroup")),
        AccountItem("10", "Vanguard Systems", "Account", listOf("VanguardTech", "VST", "FrontierSolutions", "PioneerGroup")),
        AccountItem("11", "OmniCorp International", "Account", listOf("OmniGlobal", "OCI", "UniversalCorp", "PanoramaGroup")),
        AccountItem("12", "Zenith Holdings", "Account", listOf("ZenithCapital", "ZHG", "PeakInvest", "ApexGroup")),
        AccountItem("47", "Nano Filter", "Item", listOf("MicroStrainer", "AtomicSieve", "ParticleGate", "MoleculeScreen")),
        AccountItem("48", "Hover Board", "Item", listOf("FloatDeck", "AirSkate", "LevitationPad", "AntiGravBoard")),
        AccountItem("49", "Smart Ink", "Item", listOf("DigitalPen", "E-Ink", "ProgrammablePigment", "iWrite")),
        AccountItem("50", "Thermal Regulator", "Item", listOf("TempMaster", "ClimateControl", "HeatMod", "ThermoBalance")),
        AccountItem("51", "Bio Printer", "Item", listOf("OrganMaker", "CellPrinter", "TissueBuilder", "LifePrinter")),
        AccountItem("52", "Quantum Drive", "Item", listOf("SpaceWarper", "FTL Engine", "HyperDrive", "StarJumper")),
        AccountItem("53", "Neural Headset", "Item", listOf("MindReader", "BrainGear", "ThoughtCap", "CerebralLink")),
        AccountItem("54", "Nano Armor", "Item", listOf("AtomicShield", "MicroMail", "PicoPlate", "QuantumGuard")),
        AccountItem("55", "Smart Soil", "Item", listOf("GrowthMatrix", "TerraBoost", "BioEarth", "FarmTech")),
        AccountItem("56", "Holographic Keyboard", "Item", listOf("AirType", "LightBoard", "ProjectionKeys", "VirtualInput")),
        AccountItem("57", "Solar Paint", "Item", listOf("PowerCoat", "SunPaint", "PhotoFinish", "EnergyVarnish")),
        AccountItem("58", "AI Camera", "Item", listOf("SmartLens", "ThinkShutter", "CogniCapture", "IntelOptics")),
        AccountItem("59", "Water Generator", "Item", listOf("AquaMaker", "HydroGen", "DewCreator", "MoistureFarm")),
        AccountItem("60", "Memory Implant", "Item", listOf("RecallChip", "NeuralStorage", "BrainDrive", "CerebralSSD")),
        AccountItem("70", "Self-Healing Glass", "Item", listOf("RepairPane", "MendScreen", "AutoFix Crystal", "ReboundShard"))
    )
}